language: node_js
node_js:
  - 18
os:
  - linux
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH=$HOME/.yarn/bin:$PATH
# See https://code.visualstudio.com/api/working-with-extensions/continuous-integration#travis-ci
install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - yarn
cache:
  yarn: true
script: yarn test:ci
