name: Open VSX Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build & deploy to Open VSX
        uses: actions/setup-node@v1
        with:
          node-version: 16.4.0
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn deploy:ovsx -p ${{ secrets.OVSX_ACCESS_TOKEN }}
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
